# Generated by Django 4.1.3 on 2022-11-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='RelatedGroup',
            field=models.ManyToManyField(related_name='Group', to='auth.group'),
        ),
    ]
