# Generated by Django 4.1.3 on 2022-11-22 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('bi', 'Bidirectional'), ('src', 'Source'), ('dst', 'Destination')], max_length=3)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='GroupAccess', to='auth.group')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.dicomnode')),
            ],
        ),
    ]
