# Generated by Django 4.1.3 on 2022-11-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
