# Generated by Django 4.1.3 on 2022-11-29 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('groups', '0002_access_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='group',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='GroupAccess', to='auth.group'),
        ),
    ]
