# Generated by Django 4.1.3 on 2022-11-29 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
        ('groups', '0003_alter_access_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access_type',
            field=models.CharField(choices=[('bi', 'Bidirectional'), ('src', 'Source'), ('dst', 'Destination')], editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='access',
            name='node',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='mysite.dicomnode'),
        ),
    ]
