# Generated by Django 4.1.3 on 2022-12-05 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_alter_access_access_type_alter_access_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='access_type',
            field=models.CharField(choices=[('src', 'Source'), ('dst', 'Destination')], editable=False, max_length=3),
        ),
    ]
