[tool.poetry]
name = "perms"
version = "0.1.0"
description = ""
authors = ["LucaDulz <luca.dulz@med.uni-heidelberg.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
django = "^4.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
